export const countries = [
    { label: "Afghanistan", value: "Afghanistan" },
    { label: "Albania", value: "Albania" },
    { label: "Algeria", value: "Algeria" },
    { label: "Argentina", value: "Argentina" },
    { label: "Australia", value: "Australia" },
    { label: "Bangladesh", value: "Bangladesh" },
    { label: "Brazil", value: "Brazil" },
    { label: "Canada", value: "Canada" },
    { label: "China", value: "China" },
    { label: "Egypt", value: "Egypt" },
    { label: "France", value: "France" },
    { label: "Germany", value: "Germany" },
    { label: "India", value: "India" },
    { label: "Indonesia", value: "Indonesia" },
    { label: "Italy", value: "Italy" },
    { label: "Japan", value: "Japan" },
    { label: "Mexico", value: "Mexico" },
    { label: "Netherlands", value: "Netherlands" },
    { label: "Nigeria", value: "Nigeria" },
    { label: "Pakistan", value: "Pakistan" },
    { label: "Peru", value: "Peru" },
    { label: "Philippines", value: "Philippines" },
    { label: "Russia", value: "Russia" },
    { label: "Saudi Arabia", value: "Saudi Arabia" },
    { label: "South Africa", value: "South Africa" },
    { label: "South Korea", value: "South Korea" },
    { label: "Spain", value: "Spain" },
    { label: "Sweden", value: "Sweden" },
    { label: "Switzerland", value: "Switzerland" },
    { label: "Thailand", value: "Thailand" },
    { label: "Turkey", value: "Turkey" },
    { label: "Ukraine", value: "Ukraine" },
    { label: "United Kingdom", value: "United Kingdom" },
    { label: "United States", value: "United States" },
    { label: "Vietnam", value: "Vietnam" },
    { label: "Yemen", value: "Yemen" },
    { label: "Albania", value: "Albania" },
    { label: "Angola", value: "Angola" },
    { label: "Bangladesh", value: "Bangladesh" },
    { label: "Belgium", value: "Belgium" },
    { label: "Chile", value: "Chile" },
    { label: "Colombia", value: "Colombia" },
    { label: "Czech Republic", value: "Czech Republic" },
    { label: "Denmark", value: "Denmark" },
    { label: "Ethiopia", value: "Ethiopia" },
    { label: "Finland", value: "Finland" },
    { label: "Greece", value: "Greece" },
    { label: "Hungary", value: "Hungary" },
    { label: "Ireland", value: "Ireland" },
    { label: "Kenya", value: "Kenya" },
    { label: "Malaysia", value: "Malaysia" },
    { label: "Morocco", value: "Morocco" },
    { label: "Norway", value: "Norway" },
    { label: "Portugal", value: "Portugal" },
    { label: "Romania", value: "Romania" },
    { label: "Singapore", value: "Singapore" },
    { label: "Tanzania", value: "Tanzania" },
];
